export enum BackendErrorCodes {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  USER_NOT_FOUND_ERROR = 'USER_NOT_FOUND_ERROR',
  INVALID_TOKEN_ERROR = 'INVALID_TOKEN_ERROR',
  USER_NOT_AUTHORIZED_ERROR = 'USER_NOT_AUTHORIZED_ERROR',
  INVALID_EMAIL_OR_PASSWORD = 'INVALID_EMAIL_OR_PASSWORD',
  PENDING_AUTHORIZATION = 'PENDING_AUTHORIZATION',
  GOOGLE_AUTH_FAILED = 'GOOGLE_AUTH_FAILED',

  ZOD_VALIDATION_ERROR = 'ZOD_VALIDATION_ERROR',

  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  CNPJ_ALREADY_REGISTERED = 'CNPJ_ALREADY_REGISTERED',
  AVATAR_MUST_BE_IMAGE = 'AVATAR_MUST_BE_IMAGE',
  ACCOUNT_NOT_FOUND_ERROR = 'ACCOUNT_NOT_FOUND_ERROR',
  INSTITUTION_ACCOUNT_NOT_FOUND_ERROR = 'INSTITUTION_ACCOUNT_NOT_FOUND_ERROR',
  ALREADY_FOLLOWING = 'ALREADY_FOLLOWING',
  NOT_FOLLOWING = 'NOT_FOLLOWING',
  PASSWORD_MISMATCH = 'PASSWORD_MISMATCH',
}
